version: '3.8'
services:
  redis-server:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - app-network
    volumes: 
      - redis-server:/data
volumes:
  redis-server:
    driver: local
networks:
    app-network:
      driver: bridge
