version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  test-source:
    docker:
      - image: cimg/node:22.7
      - image: cimg/redis:7.4.1
        #environment:
        #  AAA_REDIS_PASSWORD: $AAA_REDIS_PASSWORD
        command: redis-server --save 20 1 --loglevel warning --requirepass $AAA_REDIS_PASSWORD
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      #- restore_cache:
      #    keys:
      #      - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install pnpm
          command: sudo npm install -g pnpm@latest
      - run:
          name: install packages
          command: pnpm install --no-frozen-lockfile
      #- save_cache:
      #    key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      #    paths:
      #      - ~/.npm
      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Waiting for Redis to be ready
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Run Tests
          command: pnpm run ci:test
      - codecov/upload

workflows:
  test-source:
    jobs:
      - test-source

