# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.9]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        redis:
          - "7.2"

    steps:
    - uses: actions/checkout@v4
    - uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: true
        redis-version: "7.x"
        redis-conf: "requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    - run: redis-cli ping
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: apt install redis-tools
    - run: ./wait-for-redis.sh localhost:6379
    - run: npm test
